# Generated by Django 5.0.7 on 2024-08-04 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('niveis_acesso', models.CharField(choices=[('PESQUISADOR', 'Pesquisador'), ('ENGENHEIRO', 'Engenheiro'), ('ADMIN_SEGURANCA', 'Especialista de Segurança'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('FUNCIONARIO', 'Funcionário'), ('OUTRO', 'Outro')], max_length=15)),
                ('localidade', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
